### ISSUE TITLE
Wedding page small gallery make image a large popup when clicked

### ISSUE THREAD

**Issue by stellaradmin** [opscaled/vinelily#11]
On the Wedding page when you click on an image, instead of it going to a new page with a small image. can we make that a popup and enlarge the image?
![capture](https://user-images.githubusercontent.com/6233537/30405389-68637c72-98a0-11e7-89b9-df62e8bae147.JPG)

**Comment by anubhavsinha** [comment]
I think what we want is a light box kind of solution here. I guess we need a design for light box on this page. The look and feel. And may be some handy features like Pinterest share etc.
