### ISSUE TITLE
Use this image for the Corporate and Family header image

### ISSUE THREAD

**Issue by stellaradmin** [opscaled/vinelily#19]
Can we use a close up of this image? https://drive.google.com/open?id=0BztpRLaklE_vT20wSnVwVDJfTHc
![capture](https://user-images.githubusercontent.com/6233537/30406094-7a9d0c2e-98a4-11e7-9fb2-6caa2d99019a.JPG)

**Comment by Sidhi-dhall** [comment]
As this image is vertical and we want a horizontal image, so I created a new image, please check this and let me know should I use this image as header image or any other image

https://cdn.shopify.com/s/files/1/2257/6491/files/background4_7dd7e1b3-0fc2-42ed-9e02-0f4d208353f0.png?12474966784768017749

**Comment by stellaradmin** [comment]
I have tried to change this image and after saving it when I viewed the site the old image is still there.  Please show me (DeAndre), what I am doing wrong. Trying to change it to this image:
corporate-bg_2x_f39fd366-b7f7-4711-b9ba-c75b1618171c.jpg

**Comment by Sidhi-dhall** [comment]
Deandre could you please send the image also
