### ISSUE TITLE
Fix search interface

### ISSUE THREAD

**Issue by anubhavsinha** [opscaled/vinelily#24]

**Comment by lelab144** [comment]
this sounds like a bug, not a change request.  We never designed search to open to a white page.

**Comment by anubhavsinha** [comment]
@lelab144 Okay, changed to a bug.

**Comment by anubhavsinha** [comment]
@lelab144 Okay, this is some thing that was implemented in a way that we do not want it to be. "We never designed search to open to a white page". Yes, but, we never designed it to work through a search bar either. I couldn't find any communication about how it should work. So, the feature works but needs to be implemented in a different way now. It's not a bug. There needs to be a clear communication about the specs.

**Comment by stellaradmin** [comment]
Resolved
