### ISSUE TITLE
No image for the three subscriptions in checkout cart

### ISSUE THREAD

**Issue by stellaradmin** [opscaled/vinelily#34]
There is no image for the three subscriptions when in the shopping cart, just a blank placeholder.  Replace with an image of the VineLily van.
![img_67181](https://user-images.githubusercontent.com/6233537/31586648-92cf14e8-b188-11e7-8e61-10af960e910a.jpg)

**Comment by anubhavsinha** [comment]
We don't have design for this. We were not provided any image. @stellaradmin

**Comment by stellaradmin** [comment]
Resolved.
