### ISSUE TITLE
There should be no "child patient" or "Sibling" in the Questionnaire drop down 

### ISSUE THREAD

**Issue by stellaradmin** [opscaled/vinelily#35]
Please replace "child patient" and "Sibling" with Wedding Planner and Bride.
![img_67191](https://user-images.githubusercontent.com/6233537/31586697-43770634-b189-11e7-8253-1c291d74b577.jpg)

**Comment by anubhavsinha** [comment]
This is a change request. @stellaradmin We implemented the list what you gave us on the mail.

**Comment by stellaradmin** [comment]
Resolved
